/**
 * Anchor homography tests: recover a synthetic goal pose — image corners
 * generated by a known projective camera — and map interior image points
 * back to metric goal-plane coordinates (crossing point / GOAL? geometry).
 */
import {
  imageToWorld,
  solveAnchorHomography,
  type Point2,
} from '../anchorHomography';
import { SingularMatrixError } from '../linalg';
import { SOCCER_GOAL, TENNIS_COURT } from '../sportProfile';

/**
 * Ground-truth world -> image projective transform for the synthetic
 * scene: a mildly oblique camera on a 1280x720 frame (image y grows
 * downward, hence the negated second row).
 */
const H_WORLD_TO_IMAGE = [
  [92, 14, 260],
  [-7, -96, 560],
  [0.012, 0.005, 1],
];

function project(world: Point2): Point2 {
  const H = H_WORLD_TO_IMAGE;
  const w = H[2]![0]! * world.x + H[2]![1]! * world.y + H[2]![2]!;
  return {
    x: (H[0]![0]! * world.x + H[0]![1]! * world.y + H[0]![2]!) / w,
    y: (H[1]![0]! * world.x + H[1]![1]! * world.y + H[1]![2]!) / w,
  };
}

describe('solveAnchorHomography (synthetic goal pose)', () => {
  const imageCorners = SOCCER_GOAL.points.map((p) => project({ x: p.xM, y: p.yM }));
  const anchor = solveAnchorHomography(imageCorners, SOCCER_GOAL);

  it('fits the 4 detected corners essentially exactly', () => {
    expect(anchor.rmsErrorM).toBeLessThan(1e-8);
    expect(anchor.maxErrorM).toBeLessThan(1e-8);
    expect(anchor.errorsM).toHaveLength(4);
  });

  it('maps each image corner back to its metric goal coordinates', () => {
    for (let i = 0; i < SOCCER_GOAL.points.length; i++) {
      const world = imageToWorld(anchor, imageCorners[i]!);
      expect(world.x).toBeCloseTo(SOCCER_GOAL.points[i]!.xM, 6);
      expect(world.y).toBeCloseTo(SOCCER_GOAL.points[i]!.yM, 6);
    }
  });

  it('recovers interior goal-plane points (the crossing geometry)', () => {
    // A shot crossing 5.2 m from the left post, 1.1 m up: inside the goal.
    for (const truth of [
      { x: 5.2, y: 1.1 },
      { x: 0.3, y: 2.2 },
      { x: 3.66, y: 0.0 },
    ]) {
      const recovered = imageToWorld(anchor, project(truth));
      expect(recovered.x).toBeCloseTo(truth.x, 6);
      expect(recovered.y).toBeCloseTo(truth.y, 6);
    }
  });

  it('works for ground-plane templates too (tennis court corners)', () => {
    const courtCorners = TENNIS_COURT.points.map((p) =>
      project({ x: p.xM, y: p.yM }),
    );
    const court = solveAnchorHomography(courtCorners, TENNIS_COURT);
    const truth = { x: 5.485, y: 11.885 }; // centre of the court
    const recovered = imageToWorld(court, project(truth));
    expect(recovered.x).toBeCloseTo(truth.x, 5);
    expect(recovered.y).toBeCloseTo(truth.y, 5);
  });
});

describe('solveAnchorHomography (validation)', () => {
  it('rejects a point count that does not match the template', () => {
    expect(() => solveAnchorHomography([{ x: 0, y: 0 }], SOCCER_GOAL)).toThrow(
      /Expected 4 image points/,
    );
  });

  it('throws SingularMatrixError for collinear corners', () => {
    const collinear: Point2[] = [
      { x: 0, y: 0 },
      { x: 10, y: 10 },
      { x: 20, y: 20 },
      { x: 30, y: 30 },
    ];
    expect(() => solveAnchorHomography(collinear, SOCCER_GOAL)).toThrow(
      SingularMatrixError,
    );
  });
});
